config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/projects', to: 'projects#index'

  resources :projects do
    resources :todos, only: [:update], to: 'todos#update_todo'
  end
  # get '/projects/:id/todos/:id', to: 'todos#check_todo'
  post '/todos', to: 'todos#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :todos

  validates :title, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project

  validates :text, :project, presence: true

  default_scope { order(:created_at) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    # render json: { message: 'OK' }

    # @projects = Project.select(:id, :title)
    @projects = Project.all
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def update_todo
    @todo = Todo.find_by(id: params[:id], project_id: params[:project_id])

    #  Будут бить за это :(
    raise ActiveRecord::RecordNotFound if @todo.nil?

    if @todo.update(isCompleted: !@todo.isCompleted)
      render json: { todo: @todo, status: 'OK' }, status: 200
    else
      render json: @todo.errors, status: :unprocessable_entity
    end
  end

  def create
    if !params[:todo][:project].empty?
      @project = Project.new({ title: todo_params[:project] })

      if @project.save!
        @todo = Todo.new(todo_params.except(:project).merge!(project_id: @project.id))
        @todo.save!
      else
        render json: @project.errors, status: :unprocessable_entity
      end
    else
      @todo = Todo.new(todo_params.except(:project))
      render json: @todo.errors, status: :unprocessable_entity unless @todo.save!
    end
    redirect_to '/projects', flash: { alert: 'Item is added!' }
  end

  private

  def todo_params
    params.require(:todo).permit(:text, :isCompleted, :project_id, :project)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListOblakogroupRu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_card.html.erb
<% @projects.each do |project| %>
  <div class="column is-3">
    <div class="card">

      <header class="card-header">
        <p class="card-header-title">
          <%= project.title %>
        </p>
      </header>

      <div class="card-content">
        <div class="content">
          <dl>

            <% project.todos.each do |todo| %>
              <dt>
                <a href="<%= "/projects/#{project.id}/todos/#{todo.id}" %>"
                  id="<%= "todo-#{todo.id}" %>"
                  class="<%= 'is-strikethrough' if todo.isCompleted %>"
                  data-remote="true"
                  data-method="patch"
                  rel="nofollow"
                >
                  <label>
                    <%= check_box_tag todo.id, todo.isCompleted, todo.isCompleted %>
                    <%= todo.text %>
                  </label>
                </a>


              </dt>
            <% end %>

          </dl>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/projects/_modal_window.html.erb
<div class="modal" id="modal-js-example">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Новая задача</p>
      <button class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">

      <%= form_for :todo, url: todos_path do |form| %>
        <%#= form.collection_select :project_select, Project.order(:title), :id, :title %>
        <div class="block">
          <%= form.text_field  :text, placeholder: 'Название задачи...', class: 'input is-focused' %>
        </div>
        <div class="block">
          <%= form.text_field :project, placeholder: 'Название новой категории...', class: 'input is-hidden' %>
        </div>
        <div class="select is-fullwidth">
          <%= select(:todo, "project_id", @projects.collect {|p| [ p.title, p.id ] }, { include_blank: 'Новая категория', selected: @projects.first.id }) %>
        </div>

    </section>
    <footer class="modal-card-foot">
        <button class="button has-background-grey-light has-text-light" id="close-modal-btn">ОТМЕНА</button>
        <%= form.submit 'OK', class: "button is-info" %>
    </footer>
    <% end %>
  </div>
</div>

app/views/projects/_navbar.html.erb
<section class="hero is-info is-small">
  <div class="hero-body">
    <nav class="navbar">
      <div class="container">

      <div class="container has-text-centered">
        <p class="title">
          Задачи
        </p>
      </div>

    </div>
          <div class="navbar-end">
            <span class="navbar-item has-text-centered">
              <button class="button is-black is-inverted js-modal-trigger" data-target="modal-js-example">
                +
              </button>
            </span>
          </div>
      </nav>
  </div>
</section>

app/views/projects/index.html.erb
<%= render 'navbar' %>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">

      <%= render 'card' %>

    </div>
  </div>
</section>

<%= render 'modal_window' %>

<%= javascript_pack_tag 'todo' %>